language: clojure
sudo: required
dist: trusty
before_script:
  - ./bin/ci/install_mongodb.sh  
  - mongod --version
  - ./bin/ci/before_script.sh
script: lein do clean, javac, test
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
services:
  - mongodb
branches:
  only:
    - master
    - async-3.1.0
